import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Moralis from 'moralis'
import { ConnectButton } from '@web3modal/react'
import { GetServerSideProps } from 'next'

type Props = {
  nativeBalance?: string
  address?: string
}

export default function Home({ nativeBalance, address }: Props) {
  //  const { mutate: myFunction } = useContractWrite(contract, 'burnAndMint')

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h3>Wallet: {address}</h3>
          <h3>Native Balance: {nativeBalance} ETH</h3>
          <ConnectButton />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  // reads the api key from .env.local and starts Moralis SDK
  await Moralis.start({ apiKey: process.env.MORALIS_API_KEY })

  const address = '0x79c3e736445f9eeeCa6467103fBF3b0c924e59e0'

  const nativeBalance = await Moralis.EvmApi.balance.getNativeBalance({
    address,
  })

  return {
    props: {
      address,
      // Return the native balance formatted in ether via the .ether getter
      nativeBalance: nativeBalance.result.balance.ether,
    },
  }
}
