import {
  ConnectWallet,
  useContract,
  useContractRead,
  useContractWrite,
} from '@thirdweb-dev/react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const { contract } = useContract('0x31becf5ec3987315d2986305aee61e0c54903cdd')
  const { data: nft, isLoading, error } = useContractRead(contract, 'owner')
  console.log(error)

  //  const { mutate: myFunction } = useContractWrite(contract, 'burnAndMint')

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectWallet accentColor="#f213a4" colorMode="light" />
        {!isLoading ? nft : <p>Loading...{error}</p>}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
