import { Web3Button } from '@thirdweb-dev/react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Web3Button
          // The contract address
          contractAddress="0x424037abd63d32595bD843791ab015C31c87Cb6d"
          // Access the contract itself, perform any action you want on it:
          action={(contract) =>
            contract.erc721.mint({
              name: 'Hello world!',
              // This way, you get the benefits of the SDK
              // Image can be of type File, or any url that points to a file.
              image: 'ipfs://Qmf9csTfndWRgH2z35WUBm9jTuQKfSv1dJC9YKW6iTZkDP/0',
              description: 'Your awesome NFT',
            })
          }
          // If the function succeeds, we can do something here.
          onSuccess={(result) => console.log(result)}
          // If the function fails, we can do something here.
          onError={(error) => console.error(error)}
        >
          Mint NFT
        </Web3Button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
